[Desktop Entry]
Type=X-GNOME-Metatheme
Name=Adwaita-Manjaro-light
Comment=There is only one for the one only
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=Adwaita-Manjaro-light
Type=X-GNOME-Metatheme
Comment=There is only one for the one only
Encoding=UTF-8
GtkTheme=Adwaita-Manjaro-light
MetacityTheme=Adwaita-Manjaro-light
IconTheme=gnome
CursorTheme=Adwaita
CursorSize=24
CursorTheme=DMZ-Black
ButtonLayout=close,minimize,maximize:
